In [2]:
import numpy as np

In [3]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)

In [4]:
multiply = arr *4
print("Arr multiplied by 4:", multiply)

Arr multiplied by 4: [ 80 108  36  48 124  68  16 200 156 140]


In [5]:
print ("Mean: ",np.mean(arr))

Mean:  24.4


In [6]:
print ("Median: ",np.median(arr))

Median:  23.5


In [7]:
print ("standard Deviation: ",np.std(arr))

standard Deviation:  13.828955130450023


In [8]:
min_num= np.argmin(arr)
max_num = np.argmax(arr)
print("Index of smallest value:", min_num)
print("Index of largest value:", max_num)

Index of smallest value: 6
Index of largest value: 7


In [9]:
print("Smallest value (using index):", arr[min_num])
print("Largest value (using index):", arr[max_num])

Smallest value (using index): 4
Largest value (using index): 50


In [10]:
print("Minimum value:", np.min(arr))
print("Maximum value:", np.max(arr))

Minimum value: 4
Maximum value: 50


In [11]:
print("Do they match?",arr[min_num] == np.min(arr) and arr[max_num] == np.max(arr))


Do they match? True


In [12]:
greater_20 = arr[arr > 20]
print("Values greater than 20:", greater_20)

Values greater than 20: [27 31 50 39 35]


In [13]:
matrix = np.array([
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
])

In [14]:
print("Shape:", matrix.shape)
print("Rows:", matrix.shape[0])
print("Columns:", matrix.shape[1])

Shape: (3, 4)
Rows: 3
Columns: 4


In [15]:
print("Third column:", matrix[:, 2])

Third column: [17 14 19]


In [16]:
print("Second row:", matrix[1])

Second row: [ 8 21 14  3]


In [17]:
print("Multiplied by 2:\n", matrix * 2)

Multiplied by 2:
 [[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [18]:
print("Column means:", np.mean(matrix, axis=0))

Column means: [ 6.33333333 15.33333333 16.66666667  7.66666667]


In [19]:
print("Overall mean:", np.mean(matrix))

Overall mean: 11.5


In [20]:
print("Max of each row:", np.max(matrix, axis=1))
print("Min of each column:", np.min(matrix, axis=0))

Max of each row: [17 21 19]
Min of each column: [ 5 12 14  3]


In [21]:
flatten_array= matrix.flatten()
print("Flattened array:", flatten_array)
print("New shape:", flatten_array.shape)

Flattened array: [ 5 12 17  9  8 21 14  3  6 13 19 11]
New shape: (12,)


In [22]:
min_num = np.argmin(matrix)
max_num = np.argmax(matrix)
print("Flat index of min:", min_num)
print("Flat index of max:", max_num)

Flat index of min: 7
Flat index of max: 5


In [23]:
min_coords = np.unravel_index(min_num, matrix.shape)
max_coords = np.unravel_index(max_num, matrix.shape)
print("Coordinates of min:", min_coords)
print("Coordinates of max:", max_coords)

Coordinates of min: (np.int64(1), np.int64(3))
Coordinates of max: (np.int64(1), np.int64(1))


In [24]:
greater_15 = matrix[matrix > 15]
print("Values > 15:", greater_15)

Values > 15: [17 21 19]


In [26]:
sorted_matrix = np.sort(matrix, axis=1)
print("Row-wise sorted matrix:\n", sorted_matrix)


Row-wise sorted matrix:
 [[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [27]:
arr_second = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
          return False
    return True
def rows_with_prime(arr_second):
    return arr_second[np.any(np.vectorize(is_prime)(arr_second), axis=1)]
print(rows_with_prime(arr_second))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [28]:
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, ::2] = 1
    board[1::2, 1::2] = 1
    return board
print(checkerboard())

def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, 1::2] = 1
    board[1::2, ::2] = 1
    return board
print(reverse_checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [29]:
arr = np.array(["galaxy", "clusters"])
def expansion(arr, n):
    spaces = " " * n
    return np.array([spaces.join(word) for word in arr])
print(expansion(arr, 3))

['g   a   l   a   x   y' 'c   l   u   s   t   e   r   s']


In [30]:
np.random.seed(123)
arr = np.random.randint(500, 2000, (5, 5))
print(arr)
def secondDimmest(arr):
    sorted_arr = np.sort(arr, axis=1)
    return sorted_arr[:, -2]
print(secondDimmest(arr))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
